### ISSUE TITLE
Please make a new release for dovecot 2.3.17 compatibility

### ISSUE THREAD

**Issue by thomask77** [slusarz/dovecot-fts-flatcurve#17]
Hi!

I just tried to update my NixOS mail server, but noticed that the last release 0.1.0 doesn't work with dovecot 2.3.17.

Can you please tag 0.1.1 or similar?

**Comment by slusarz** [comment]
There are several issues currently open that are being analyzed, so a new tagged release doesn't seem appropriate at the moment.

It might be easier if I setup Github Actions to produce assets after every run.  Would that be useful?  Is there a reason you can't build from github source directly?

**Comment by thomask77** [comment]
Not a big problem, automated asset generation is not required.
I can build from github commits just fine, and just give it a version number like `0.1.0+20211223` or something.

The release should of course wait until the known issues are fixed.

**Comment by slusarz** [comment]
v0.2.0 has been released.
