### ISSUE TITLE
Assignment bug in if statement

### ISSUE THREAD

**Issue by darylrichards** [slusarz/dovecot-fts-flatcurve#24]
Just testing this software, and found a likely bug in an if statement.

fts-backend-flatcurve-xapian.cpp, line 607:

`else if (errno = ENOENT)` should likely be `else if (errno == ENOENT)`

**Comment by slusarz** [comment]
Good catch.  This was already fixed in the merged 2.4 code but was not backported here.  Fixed in f5674d130d4c3b4e41e02e6710d28d09beb06426.
