### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by ghtm2** [slusarz/dovecot-fts-flatcurve#31]
Hi,

I'm trying to build this on el9, but the build is failing on:
```
fts-backend-flatcurve-xapian.cpp: In function 'int fts_flatcurve_xapian_lock(flatcurve_fts_backend*)':
fts-backend-flatcurve-xapian.cpp:517:13: error: 'struct file_create_settings' has no member named 'lock_settings'
  517 |         set.lock_settings.close_on_free = TRUE;
      |             ^~~~~~~~~~~~~
fts-backend-flatcurve-xapian.cpp:518:13: error: 'struct file_create_settings' has no member named 'lock_settings'
  518 |         set.lock_settings.unlink_on_free = TRUE;
      |             ^~~~~~~~~~~~~
fts-backend-flatcurve-xapian.cpp:519:13: error: 'struct file_create_settings' has no member named 'lock_settings'
  519 |         set.lock_settings.lock_method = backend->parsed_lock_method;
      |             ^~~~~~~~~~~~~
```

The distro is shipping dovecot 2.3.16 and xapian 1.4.18, so the requirements are met according to the front page.
Any idea what the problem may be?

**Comment by slusarz** [comment]
It looks like the API for Dovecot core's lib/file-create-locked.h changed in September 2021, https://github.com/dovecot/core/commit/083439ed737b8a8edbfec28fce7b59e003983fc1 .  Which means it would have appeared in v2.3.17.

Given the current state of this project, I don't see a need to try to fix the latest code to try to work with old, outdated versions of Dovecot.  So your best option is to use a release of flatcurve that supports core v2.3.16 - such as https://github.com/slusarz/dovecot-fts-flatcurve/releases/tag/v0.2.0.

I've gone and marked v0.3.0 as requiring v2.3.17+, and I will add a note to README that current HEAD requires that as well.
