### ISSUE TITLE
Separate directory for indexing?

### ISSUE THREAD

**Issue by ser** [slusarz/dovecot-fts-flatcurve#34]
Why flatcurve does not have an option to store its data in a separate location to mail content? 

It's a huge problem for me, as I keep maildirs on slow NFS drive but I could use local fast SSD for indexing. 

Xapian extension was perfectly OK with such a scenario.

**Comment by pgnd** [comment]
flatcurve stores its index data in dovecot's assigned index directory.

https://doc.dovecot.org/configuration_manual/mail_location/#index-files

> 
> "Index files are by default stored under the same directory as mails.
> You may want to change the index file location if you’re using [NFS](https://doc.dovecot.org/configuration_manual/nfs/#nfs) or if you’re setting up [Shared mailboxes](https://doc.dovecot.org/configuration_manual/shared_mailboxes/#shared-mailboxes).
> 
> You can change the index file location by adding :INDEX=<path> to mail_location"
>

**Comment by slusarz** [comment]
Duplicate of #33

**Comment by ser** [comment]
You are right, but it's not easy to find that information even if I am an experienced dovecot user. Especially after upgrading from Xapian search module. IMHO at least one sentence in flatcurve docs should mention it.

**Comment by pgnd** [comment]
https://github.com/slusarz/dovecot-fts-flatcurve#user-content-data-storage

"Data Storage

Xapian search data is stored separately for each mailbox.

The data is stored under a 'fts-flatcurve' directory in the
Dovecot index file location for the mailbox."
^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ser** [comment]
Exactly this is why I submitted this issue, understanding this as the location is bound to the mailbox.

**Comment by ser** [comment]
For example, solution would be to link the phrase "Dovecot index file location for the mailbox" to "https://doc.dovecot.org/configuration_manual/mail_location/#index-files"

**Comment by slusarz** [comment]
Added link to the README, as suggested.
