### ISSUE TITLE
Using fts-flatcure with Dovecot 2.3.13 / Debian Bookworm

### ISSUE THREAD

**Issue by tilllt** [slusarz/dovecot-fts-flatcurve#45]
I am really looking forward to Dovecot 2.4 with fts-flatcurve, but in the meantime on Debian Bookworm, i tried to compile it manually.
Per the readme file i downloaded the source code for fts-flatcurve 0.2.0 compiled and installed it, leading dovcecot 2.3.13 (the default version on debian bookworm) to report this:

`doveadm fts-flatcurve check

Fatal: Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_flatcurve_plugin.so: Module is for different ABI version 2.3.ABIv19(2.3.19.1) (we have 2.3.ABIv13(2.3.13))`

Since there is no Dovecot CE Version for Debian Bookworm yet, i am kind of stuck on dovecot 2.3.13 - but the readme suggests fts-flatcurve 0.2.0 should work with that version, only it doesnt.

am i missing something?

**Comment by slusarz** [comment]
You need to compile against Dovecot 2.3.13 source.  As the error message shows, you compiled against 2.3.19.1 but are trying to run the plugin on a 2.3.13 system.  This won't work, regardless of the flatcurve version.

Although I'm a bit confused - I thought bookworm ships with Dovecot 2.3.19.1?  (bullseye shipped with 2.3.13) https://packages.debian.org/bookworm/dovecot-core

**Comment by tilllt** [comment]
I think I ran ./configure before updating Debian, it works not!
