### ISSUE TITLE
Example config anywhere?

### ISSUE THREAD

**Issue by tilllt** [slusarz/dovecot-fts-flatcurve#46]
I cant find a complete config example for fts-flatcurve. When I just use the config lines from the documentation, it complains about language and tokenizers missing, is there a complete working example somewhere?

**Comment by slusarz** [comment]
The top of the configuration page links to the Dovecot core FTS configuration page, which is required reading.

But I added example settings also now (although you should really be reading the doc.dovecot.org page about these).

**Comment by tilllt** [comment]
Feel free to point out where it mentiones the minimum required parameters?

https://doc.dovecot.org/configuration_manual/fts/
