### ISSUE TITLE
Error: fts: Failed to initialize backend 'flatcurve': Unknown backend

### ISSUE THREAD

**Issue by tilllt** [slusarz/dovecot-fts-flatcurve#47]
Sorry for all the issues, but after compilation and configuration errors the next problem arises.

/var/log/error.log now mentions 

`Error: fts: Failed to initialize backend 'flatcurve': Unknown backend`

in /usr/lib/dovecot/modules i have
```

-rw-r--r-- 1 root root 1241300 Nov  8 18:42 lib21_fts_flatcurve_plugin.a
-rwxr-xr-x 1 root root    1104 Nov  8 18:42 lib21_fts_flatcurve_plugin.la
-rwxr-xr-x 1 root root  623824 Nov  8 18:42 lib21_fts_flatcurve_plugin.so
```

**Comment by slusarz** [comment]
By default configure parameters, those files should be under /usr/lib/dovecot

**Comment by slusarz** [comment]
Closing due to no feedback (and this appears to be an installation error).

**Comment by powercycle** [comment]
I also got this error when all the required flatcurve settings weren't present.
