### ISSUE TITLE
Searches with UNDELETED don't use index

### ISSUE THREAD

**Issue by omolenkamp** [slusarz/dovecot-fts-flatcurve#6]
After switching from an older Dovecot version with fts-lucene to Dovecot 2.3.16 with fts-flatcurve, I noticed that searches from Thunderbird were a lot slower than before. It turns out Thunderbird does its searches with `UNDELETED`, and the index simply isn't used for those searches.

Without `UNDELETED`, the index is being used:
```
. UID SEARCH BODY onmiddellijk
* SEARCH 499 1160 1175 1187 1196 1198 1265 1341 1631 1838 1840 2323 2327 2331 2344 2346 2347 2349 2416 2488 5126 5135 5844
. OK Search completed (0.033 + 0.000 + 0.032 secs).
```
With `UNDELETED`, the index isn't used and the search is a lot slower:
```
. UID SEARCH UNDELETED BODY onmiddellijk
* OK Searched 55% of the mailbox, ETA 0:07
* SEARCH 499 1160 1175 1187 1196 1198 1265 1341 1631 1838 1840 2323 2327 2331 2344 2346 2347 2349 2416 2488 5126 5135 5844
. OK Search completed (17.956 + 0.001 + 0.072 secs).
```

**Comment by slusarz** [comment]
Confirmed.  Flatcurve was not ignoring this search argument - instead, it was treating as an unknown argument and was invalidating the entire search, forcing a slow, sequential search.  Fix by ignoring the argument if it is marked with "no_fts".
